Repository GrooveHQ/design-system, pull requests merged in 2020-03, with the labels that each got.

#58 Animations
  jsconfig.json
  package.json
  src/components/AvatarList/AvatarList.js
  src/components/Badge.js
  src/components/Button.js
  src/components/Card.js
  src/components/Container.js
  src/components/ContainerContext.js
  src/components/Dropdown.js
  src/components/Forms/CheckRadioBase.js
  src/components/Forms/Checkbox.js
  src/components/Forms/Field.js
  src/components/Forms/Input.js
  src/components/Forms/Radio.js
  src/components/Header.js
  src/components/Heading.js
  src/components/Icon.js
  src/components/Label.js
  src/components/Paragraph.js
  src/components/StaggeredList.js
  src/components/StaggeredList.stories.js
  src/components/Tooltip.js
  src/components/index.js
  src/components/shared/animation.js
  src/components/shared/forms.js
  yarn.lock
Labels: enhancement, major, release

#60 Various Design Polish
  src/components/Avatar.js
  src/components/AvatarList/AvatarList.js
  src/components/Badge.js
  src/components/Container.js
  src/components/Dropdown.js
  src/components/Forms/Checkbox.js
  src/components/Forms/Field.js
  src/components/Forms/Radio.js
  src/components/Forms/TextArea.js
  src/components/Header.js
  src/components/Icon.js
  src/components/Loader.js
  src/components/Paragraph.js
  src/components/StaggeredList.js
  src/components/StaggeredList.stories.js
  src/components/shared/animation.js
  src/components/shared/forms.js
  src/components/shared/styles.js
  src/utils/useScrollbarWidth.js
Labels: enhancement, patch, release

#61 Extract base colors into CSS variables
  .storybook/config.js
  src/Intro.stories.mdx
  src/components/Avatar.js
  src/components/Avatar.stories.js
  src/components/Badge.js
  src/components/Button.js
  src/components/Button.stories.js
  src/components/Card.js
  src/components/Container.js
  src/components/Dropdown.js
  src/components/FlexItems.stories.js
  src/components/Forms/CheckRadioBase.js
  src/components/Forms/Checkbox.js
  src/components/Forms/Input.js
  src/components/Forms/Radio.js
  src/components/Forms/Select.js
  src/components/Header.js
  src/components/Heading.js
  src/components/Icon.js
  src/components/Icon.stories.js
  src/components/Label.js
  src/components/Paragraph.js
  src/components/Tooltip.js
  src/components/shared/forms.js
  src/components/shared/global.js
  src/components/shared/styles.js
Labels: major

#62 Upgrade Storybook to 5.3.17
  package.json
  yarn.lock
Labels: patch

#63 Add the option to reverse a FlexContainer
  src/components/FlexContainer.js
  src/components/FlexItem.js
Labels: enhancement, minor

#64 Fix bug in flex container cascading div selector
  src/components/FlexContainer.js
Labels: bug, patch

#65 Add header and median proptypes for container
  src/components/Container.js
Labels: documentation, patch

#66 Simplify branding in Container component
  src/components/Container.js
Labels: internal, minor
