Repository GrooveHQ/design-system, pull requests merged in 2020-06, with the labels that each got.

#79 Fix bug where cursor flickers on button hover
  src/components/Button.js
Labels: bug, patch, release

#80 Refactor badge
  src/components/Badge.js
  src/components/Badge.stories.js
Labels: bug, enhancement, patch, release

#83 Disable proptype for AvatarList children
  src/components/AvatarList/AvatarList.js
Labels: bug, internal, patch, release

#82 Fix header overlap scrolling
  src/components/Container.js
  src/components/ContainerContext.js
  src/components/Header.js
Labels: bug, patch, release

#84 Honor padded prop for InnerContent
  package.json
  src/components/Container.js
  src/components/Forms/TextArea.js
  src/components/Forms/TextArea.stories.js
Labels: enhancement, minor, patch, release

#85 Clean up focus outlines
  src/components/Dropdown.js
  src/components/GlobalKeyboard.js
  src/components/index.js
  src/components/shared/global.js
Labels: enhancement, patch, release

#86 Specify flex-direction on container
  src/components/Container.js
Labels: bug, patch, release
