Repository GrooveHQ/design-system, pull requests merged in 2021-02, with the labels that each got.

#104 Upgrade framer and remove peer dependencies
  package.json
  src/components/Badge.js
  src/components/Forms/Field.js
  yarn.lock
Labels: dependencies, minor, release

#105 Support mobile layouts
  src/components/Badge.js
  src/components/Container.js
  src/components/Header.js
  src/components/shared/global.js
Labels: enhancement, minor, release

#106 Fix compact hover
  src/components/AvatarList/AvatarList.js
  src/components/Badge.js
  src/components/Icon.js
Labels: patch, release
